# Generated by Django 2.1.1 on 2018-10-03 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chauser',
            old_name='instructor_profile',
            new_name='instructor',
        ),
    ]
