# Generated by Django 2.1.1 on 2018-10-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20181003_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='chauser',
            name='has_set_password',
            field=models.BooleanField(default=False),
        ),
    ]
