# Generated by Django 2.1.1 on 2018-11-02 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20181102_2141'),
        ('profiles', '0003_chauser_has_set_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instructor_members', to='groups.InstructorGroup'),
        ),
        migrations.AddField(
            model_name='studentmembership',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='groups.KlassTeam'),
        ),
        migrations.AlterField(
            model_name='assistantmembership',
            name='klass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='klasses.Klass'),
        ),
    ]
