# Generated by Django 2.1.1 on 2018-12-13 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klasses', '0011_auto_20181127_2226'),
        ('profiles', '0004_auto_20181102_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chauser',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='chauser',
            unique_together={('email', 'username')},
        ),
        migrations.AlterUniqueTogether(
            name='studentmembership',
            unique_together={('user', 'klass', 'student_id')},
        ),
    ]
