# Generated by Django 2.1.1 on 2019-01-31 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20190131_0043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chauser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterUniqueTogether(
            name='chauser',
            unique_together=set(),
        ),
    ]
