# Generated by Django 2.1.1 on 2019-02-07 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20190131_0059'),
        ('groups', '0005_auto_20181102_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmembership',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='groups.Team'),
        ),
    ]
