# Generated by Django 2.1.1 on 2019-03-06 22:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_passwordresetrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetrequest',
            name='key',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
