# Generated by Django 2.1.1 on 2019-06-24 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_githubuserinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='chauser',
            name='github_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='profiles.GithubUserInfo'),
        ),
    ]
