# Generated by Django 2.1.1 on 2019-06-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_chauser_github_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubuserinfo',
            name='access_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
