# Generated by Django 2.1.1 on 2019-07-25 20:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_githubuserinfo_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='date_promoted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
