# Generated by Django 2.1.1 on 2018-09-19 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
        ('klasses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='klass',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='klasses', to='profiles.Instructor'),
        ),
        migrations.AddField(
            model_name='klass',
            name='students',
            field=models.ManyToManyField(through='profiles.StudentMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='klass',
            name='teacher_assistants',
            field=models.ManyToManyField(through='profiles.AssistantMembership', to='profiles.Instructor'),
        ),
    ]
