# Generated by Django 2.1.1 on 2018-10-05 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('klasses', '0003_auto_20181005_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='klass',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='klass',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
