# Generated by Django 2.1.1 on 2018-10-05 18:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('klasses', '0004_auto_20181005_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klass',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='klass',
            name='modified',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
