# Generated by Django 2.1.1 on 2018-10-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klasses', '0005_auto_20181005_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='klass',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='klass',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
