# Generated by Django 2.1.1 on 2018-10-05 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20180919_2005'),
        ('klasses', '0006_auto_20181005_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='klass',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='klasses', to='groups.InstructorGroup'),
        ),
    ]
