# Generated by Django 2.1.1 on 2018-10-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klasses', '0007_klass_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='klass',
            name='description',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='klass',
            name='syllabus',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
