# Generated by Django 2.1.1 on 2018-10-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klasses', '0008_auto_20181005_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='klass',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
