# Generated by Django 2.1.1 on 2018-11-27 22:26

import apps.klasses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klasses', '0010_auto_20181018_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klass',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.klasses.models.upload_image),
        ),
        migrations.AlterField(
            model_name='klass',
            name='syllabus',
            field=models.FileField(blank=True, null=True, upload_to=apps.klasses.models.upload_syllabus),
        ),
    ]
