# Generated by Django 2.1.1 on 2019-04-02 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klasses', '0011_auto_20181127_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klass',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='klasses', to='groups.Group'),
        ),
        migrations.AlterField(
            model_name='klass',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klasses', to='profiles.Instructor'),
        ),
    ]
