# Generated by Django 2.1.1 on 2019-11-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klasses', '0012_auto_20190402_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klass',
            name='course_number',
            field=models.SlugField(default=None, max_length=60),
        ),
    ]
