# Generated by Django 2.2.10 on 2020-03-26 21:35

import apps.klasses.models
import chagrade.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klasses', '0014_auto_20191128_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klass',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=chagrade.storage.PublicStorage(), upload_to=apps.klasses.models.upload_image),
        ),
        migrations.AlterField(
            model_name='klass',
            name='syllabus',
            field=models.FileField(blank=True, null=True, storage=chagrade.storage.PublicStorage(), upload_to=apps.klasses.models.upload_syllabus),
        ),
    ]
