# Generated by Django 2.1.1 on 2018-09-19 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='klassteammembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='klass_team_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='klassteam',
            name='members',
            field=models.ManyToManyField(through='groups.KlassTeamMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instructorgroupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='groups.InstructorGroup'),
        ),
        migrations.AddField(
            model_name='instructorgroupmembership',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_memberships', to='profiles.Instructor'),
        ),
        migrations.AddField(
            model_name='instructorgroup',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to='profiles.Instructor'),
        ),
        migrations.AddField(
            model_name='instructorgroup',
            name='members',
            field=models.ManyToManyField(through='groups.InstructorGroupMembership', to='profiles.Instructor'),
        ),
    ]
