# Generated by Django 2.1.1 on 2018-10-17 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klasses', '0009_klass_active'),
        ('groups', '0002_auto_20180919_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='klassteam',
            name='klass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='klasses.Klass'),
        ),
    ]
