# Generated by Django 2.1.1 on 2018-11-02 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klasses', '0010_auto_20181018_1937'),
        ('groups', '0003_klassteam_klass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorgroupmembership',
            name='group',
        ),
        migrations.RemoveField(
            model_name='instructorgroupmembership',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='klassteammembership',
            name='team',
        ),
        migrations.RemoveField(
            model_name='klassteammembership',
            name='user',
        ),
        migrations.RemoveField(
            model_name='instructorgroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='klassteam',
            name='members',
        ),
        migrations.AddField(
            model_name='instructorgroup',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_template', to='klasses.Klass'),
        ),
        migrations.DeleteModel(
            name='InstructorGroupMembership',
        ),
        migrations.DeleteModel(
            name='KlassTeamMembership',
        ),
    ]
