# Generated by Django 2.1.1 on 2019-01-25 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klasses', '0011_auto_20181127_2226'),
        ('groups', '0005_auto_20181102_2156'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('name', 'klass')},
        ),
    ]
