# Generated by Django 2.1.1 on 2019-02-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_auto_20190131_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='challenge_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
