# Generated by Django 2.1.1 on 2018-09-19 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('homework', '0001_initial'),
        ('klasses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworksubmission',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_homework_submissions', to='profiles.Instructor'),
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='klass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homework_submissions', to='klasses.Klass'),
        ),
        migrations.AddField(
            model_name='homeworkgrade',
            name='evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_grades', to='profiles.Instructor'),
        ),
        migrations.AddField(
            model_name='homeworkgrade',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='grade', to='homework.HomeworkSubmission'),
        ),
        migrations.AddField(
            model_name='homeworkdefinition',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_homework_defintions', to='profiles.Instructor'),
        ),
        migrations.AddField(
            model_name='homeworkdefinition',
            name='klass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homework_defintions', to='klasses.Klass'),
        ),
    ]
