# Generated by Django 2.1.1 on 2018-10-19 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_auto_20180919_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomHomeworkQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_specific_answer', models.BooleanField(default=False)),
                ('question', models.CharField(max_length=300)),
                ('answer', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradingCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria_type', models.CharField(choices=[('score', 'Score'), ('duration', 'duration'), ('tests', 'tests')], max_length=20)),
                ('score_as_percent', models.BooleanField(default=True)),
                ('lower_range', models.IntegerField(default=0)),
                ('upper_range', models.IntegerField(default=10)),
            ],
        ),
        migrations.AddField(
            model_name='homeworkdefinition',
            name='ask_method_description',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homeworkdefinition',
            name='ask_method_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homeworkdefinition',
            name='ask_project_url',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homeworkdefinition',
            name='ask_publication_url',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homeworkdefinition',
            name='challenge_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='homeworkdefinition',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='homeworkdefinition',
            name='due_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='homeworkdefinition',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='homeworkdefinition',
            name='starting_kit_github_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='homeworkdefinition',
            name='team_based',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='submission_github_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='homeworkgrade',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='homework.HomeworkSubmission'),
        ),
        migrations.AddField(
            model_name='gradingcriteria',
            name='HomeworkDefinition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterias', to='homework.HomeworkDefinition'),
        ),
        migrations.AddField(
            model_name='customhomeworkquestion',
            name='HomeworkDefinition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_questions', to='homework.HomeworkDefinition'),
        ),
    ]
