# Generated by Django 2.1.1 on 2018-10-19 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klasses', '0010_auto_20181018_1937'),
        ('homework', '0003_auto_20181019_1958'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='homeworkdefinition',
            unique_together={('klass', 'name')},
        ),
    ]
