# Generated by Django 2.1.1 on 2018-10-23 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_chauser_has_set_password'),
        ('klasses', '0010_auto_20181018_1937'),
        ('homework', '0004_auto_20181019_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_grades', to='profiles.Instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_github_url', models.URLField(blank=True, default=None, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_homework', to='profiles.StudentMembership')),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homework_submissions', to='klasses.Klass')),
            ],
        ),
        migrations.RenameModel(
            old_name='GradingCriteria',
            new_name='Criteria',
        ),
        migrations.RenameModel(
            old_name='HomeworkDefinition',
            new_name='Definition',
        ),
        migrations.RenameModel(
            old_name='CustomHomeworkQuestion',
            new_name='Question',
        ),
        migrations.RemoveField(
            model_name='homeworkgrade',
            name='evaluator',
        ),
        migrations.RemoveField(
            model_name='homeworkgrade',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='homeworksubmission',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='homeworksubmission',
            name='klass',
        ),
        migrations.DeleteModel(
            name='HomeworkGrade',
        ),
        migrations.DeleteModel(
            name='HomeworkSubmission',
        ),
        migrations.AddField(
            model_name='grade',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='homework.Submission'),
        ),
    ]
