# Generated by Django 2.1.1 on 2018-10-23 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0005_auto_20181023_0253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criteria',
            old_name='HomeworkDefinition',
            new_name='homework_definition',
        ),
        migrations.AlterField(
            model_name='definition',
            name='klass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homework_definitions', to='klasses.Klass'),
        ),
    ]
