# Generated by Django 2.1.1 on 2018-10-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0006_auto_20181023_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='instructor_notes',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='teacher_comments',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
    ]
