# Generated by Django 2.1.1 on 2018-10-26 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klasses', '0010_auto_20181018_1937'),
        ('homework', '0008_auto_20181025_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='klass',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='homework_submissions', to='klasses.Klass'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_homeworks', to='profiles.StudentMembership'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='definition',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='homework.Definition'),
        ),
    ]
