# Generated by Django 2.1.1 on 2018-11-02 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0009_auto_20181026_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=150)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='homework.Definition')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='homework.Submission')),
            ],
        ),
        migrations.RenameField(
            model_name='criteria',
            old_name='homework_definition',
            new_name='definition',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='HomeworkDefinition',
            new_name='definition',
        ),
        migrations.RemoveField(
            model_name='criteria',
            name='criteria_type',
        ),
        migrations.RemoveField(
            model_name='criteria',
            name='score_as_percent',
        ),
        migrations.AddField(
            model_name='criteria',
            name='description',
            field=models.CharField(default='', max_length=150),
        ),
    ]
