# Generated by Django 2.1.1 on 2018-11-06 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20181102_2141'),
        ('homework', '0010_auto_20181102_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriteriaAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=150)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='homework.Criteria')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='criteria_answers', to='profiles.Instructor')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria_answers', to='homework.Submission')),
            ],
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='definition',
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='student_answers', to='homework.Question'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_answers', to='homework.Submission'),
        ),
    ]
