# Generated by Django 2.1.1 on 2018-11-08 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0014_auto_20181108_0655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteriaanswer',
            name='evaluator',
        ),
    ]
