# Generated by Django 2.1.1 on 2018-11-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0015_remove_criteriaanswer_evaluator'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='overall_grade',
            field=models.IntegerField(default=0),
        ),
    ]
