# Generated by Django 2.1.1 on 2018-11-27 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0018_auto_20181108_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.CharField(max_length=10)),
                ('remote_phase', models.CharField(max_length=10)),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracked_submissions', to='homework.Submission')),
            ],
        ),
    ]
