# Generated by Django 2.1.1 on 2018-11-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0019_submissiontracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submitted_to_challenge',
            field=models.BooleanField(default=False),
        ),
    ]
