# Generated by Django 2.1.1 on 2019-01-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0022_submission_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='text_grade',
            field=models.CharField(blank=True, default='0/0', max_length=10, null=True),
        ),
    ]
