# Generated by Django 2.1.1 on 2019-01-31 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0023_grade_text_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_grades', to='profiles.Instructor'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='homework.Question'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='homework.Submission'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_homeworks', to='profiles.StudentMembership'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='definition',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='homework.Definition'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='klass',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to='klasses.Klass'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='groups.Team'),
        ),
    ]
