# Generated by Django 2.1.1 on 2019-02-19 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_team_challenge_url'),
        ('homework', '0024_auto_20190131_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamCustomChallengeURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_url', models.URLField()),
                ('defintion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_challenge_urls', to='homework.Definition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_urls', to='groups.Team')),
            ],
        ),
    ]
