# Generated by Django 2.1.1 on 2019-02-19 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0025_teamcustomchallengeurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamcustomchallengeurl',
            old_name='defintion',
            new_name='definition',
        ),
    ]
