# Generated by Django 2.1.1 on 2019-04-02 20:26

import apps.homework.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0026_auto_20190219_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='definition',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_homework_defintions', to='profiles.Instructor'),
        ),
        migrations.AlterField(
            model_name='definition',
            name='klass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_definitions', to='klasses.Klass'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_github_url',
            field=models.URLField(blank=True, default=None, null=True, validators=[apps.homework.validators.validate_submission_github_url]),
        ),
    ]
