# Generated by Django 2.1.1 on 2019-07-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0027_auto_20190402_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submission_github_branch',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_github_commit_hash',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_github_repo',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
