# Generated by Django 2.1.1 on 2019-07-01 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0028_auto_20190701_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='submission_github_branch',
            new_name='github_branch',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='submission_github_commit_hash',
            new_name='github_commit_hash',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='submission_github_repo',
            new_name='github_repo',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='submission_github_url',
            new_name='github_url',
        ),
    ]
