# Generated by Django 2.1.1 on 2019-07-01 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0029_auto_20190701_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='github_branch',
            new_name='github_branch_name',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='github_repo',
            new_name='github_repo_name',
        ),
    ]
