# Generated by Django 2.1.1 on 2019-07-31 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0031_auto_20190723_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiontracker',
            name='finished',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='submissiontracker',
            name='score',
            field=models.DecimalField(decimal_places=3, max_digits=9, null=True),
        ),
    ]
