# Generated by Django 2.1.1 on 2019-07-31 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0032_auto_20190731_0057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissiontracker',
            old_name='finished',
            new_name='finished_successfully',
        ),
    ]
