# Generated by Django 2.1.1 on 2019-08-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0033_auto_20190731_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissiontracker',
            name='finished_successfully',
        ),
        migrations.RemoveField(
            model_name='submissiontracker',
            name='score',
        ),
        migrations.AddField(
            model_name='submissiontracker',
            name='stored_score',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='submissiontracker',
            name='stored_status',
            field=models.FloatField(null=True),
        ),
    ]
