# Generated by Django 2.1.1 on 2019-08-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0034_auto_20190802_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissiontracker',
            name='stored_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='submissiontracker',
            name='stored_status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
