# Generated by Django 2.1.1 on 2019-08-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0037_auto_20190803_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
