# Generated by Django 2.1.1 on 2019-08-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0038_auto_20190805_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, default=''),
        ),
    ]
