# Generated by Django 2.1.1 on 2019-08-19 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0039_auto_20190810_1319'),
        ('homework', '0039_auto_20190814_0146'),
    ]

    operations = [
    ]
