# Generated by Django 2.1.1 on 2019-08-19 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0040_merge_20190819_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='normalized_score',
        ),
    ]
