# Generated by Django 2.1.1 on 2019-09-30 18:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0042_auto_20190913_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='text',
        ),
        migrations.AddField(
            model_name='question',
            name='candidate_answers',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('MS', 'Checkboxes'), ('RS', 'Multiple Choice'), ('TX', 'Text Answer')], default='TX', max_length=2),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='answer',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
        ),
    ]
