# Generated by Django 2.1.1 on 2019-09-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0043_auto_20190930_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('MS', 'Checkboxes'), ('SS', 'Multiple Choice'), ('TX', 'Text Answer')], default='TX', max_length=2),
        ),
    ]
