# Generated by Django 2.1.1 on 2019-10-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0045_definition_questions_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='baseline_score',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='definition',
            name='target_score',
            field=models.FloatField(default=1.0, null=True),
        ),
    ]
