# Generated by Django 2.1.1 on 2019-10-04 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0047_auto_20191004_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionanswer',
            old_name='answers',
            new_name='answer',
        ),
    ]
