# Generated by Django 2.1.1 on 2019-11-18 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0048_auto_20191004_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='type',
            new_name='question_type',
        ),
    ]
