# Generated by Django 2.1.1 on 2019-11-26 18:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0049_auto_20191118_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='max_submisions_per_student',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='candidate_answers',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='answer',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
