# Generated by Django 2.1.1 on 2019-12-14 00:09

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0051_auto_20191211_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='max_submissions_per_student',
            field=models.IntegerField(default=20, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='candidate_answers',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='answer',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
