# Generated by Django 2.1.15 on 2020-02-07 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0052_auto_20191214_0009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='definition',
            options={'ordering': ['name']},
        ),
    ]
