# Generated by Django 2.1.15 on 2020-02-21 07:43

import apps.homework.models
from django.db import migrations, models


class Migration(migrations.Migration):

    #replaces = [('homework', '0053_auto_20200213_1637'), ('homework', '0054_submission_jupyter_notebook'), ('homework', '0055_submission_jupyter_score')]

    dependencies = [
        ('homework', '0052_auto_20191214_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='jupyter_notebook_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='definition',
            name='jupyter_notebook_highest',
            field=models.FloatField(default=1.0, null=True),
        ),
        migrations.AddField(
            model_name='definition',
            name='jupyter_notebook_lowest',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='jupyter_notebook',
            field=models.FileField(blank=True, null=True, upload_to=apps.homework.models.upload_jupyter_notebook),
        ),
        migrations.AddField(
            model_name='submission',
            name='jupyter_score',
            field=models.FloatField(null=True),
        ),
    ]
