# Generated by Django 2.2.10 on 2020-04-24 20:21

import apps.homework.models
import chagrade.storage
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0052_auto_20191214_0009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='definition',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='definition',
            name='jupyter_notebook_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='definition',
            name='jupyter_notebook_highest',
            field=models.DecimalField(decimal_places=1, default=10.0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='definition',
            name='jupyter_notebook_lowest',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='jupyter_notebook_grade',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='needs_review',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='jupyter_notebook',
            field=models.FileField(blank=True, null=True, storage=chagrade.storage.PublicStorage(), upload_to=apps.homework.models.upload_jupyter_notebook),
        ),
        migrations.AddField(
            model_name='submission',
            name='jupyter_score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='reporting_messages',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='criteriaanswer',
            name='score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='grade',
            name='instructor_notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='overall_grade',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='grade',
            name='teacher_comments',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='text_grade',
            field=models.CharField(blank=True, default='0/0', max_length=20, null=True),
        ),
    ]
