# Generated by Django 2.2.10 on 2020-04-27 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0053_auto_20200424_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MS', 'Checkboxes'), ('SS', 'Multiple Choice'), ('TX', 'Text Answer'), ('UL', 'URL Answer')], default='TX', max_length=2),
        ),
    ]
