# Generated by Django 2.1.15 on 2020-02-24 07:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0053_auto_20200213_1637_squashed_0055_submission_jupyter_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='reporting_messages',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
