# Generated by Django 2.1.15 on 2020-02-25 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0053_auto_20200207_1949'),
        ('homework', '0054_submission_reporting_messages'),
    ]

    operations = [
    ]
