# Generated by Django 2.2.10 on 2020-03-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0055_merge_20200225_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='instructor_notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='teacher_comments',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
