# Generated by Django 2.2.10 on 2020-03-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0055_merge_20200225_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
    ]
