# Generated by Django 2.2.10 on 2020-05-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0056_auto_20200507_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('question',)},
        ),
        migrations.AlterField(
            model_name='definition',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
