# Generated by Django 2.2.10 on 2020-04-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0056_auto_20200317_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
