# Generated by Django 2.2.10 on 2020-03-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0057_auto_20200312_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='jupyter_notebook_grade',
            field=models.FloatField(null=True),
        ),
    ]
