# Generated by Django 2.2.10 on 2020-03-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0058_grade_jupyter_notebook_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='text_grade',
            field=models.CharField(blank=True, default='0/0', max_length=20, null=True),
        ),
    ]
