# Generated by Django 2.2.10 on 2020-03-17 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0059_auto_20200312_1936'),
        ('homework', '0056_auto_20200317_0034'),
    ]

    operations = [
    ]
