# Generated by Django 2.2.10 on 2020-03-26 21:35

import apps.homework.models
import chagrade.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0060_merge_20200317_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='jupyter_notebook',
            field=models.FileField(blank=True, null=True, storage=chagrade.storage.PublicStorage(), upload_to=apps.homework.models.upload_jupyter_notebook),
        ),
    ]
