# Generated by Django 2.2.10 on 2020-04-23 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0057_auto_20200422_2132'),
        ('homework', '0061_auto_20200326_2135'),
    ]

    operations = [
    ]
