# Generated by Django 2.2.10 on 2020-04-23 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0062_auto_20200421_1816'),
        ('homework', '0062_merge_20200423_1518'),
    ]

    operations = [
    ]
