# Generated by Django 2.2.10 on 2020-04-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0063_merge_20200423_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='jupyter_notebook_highest',
            field=models.DecimalField(decimal_places=1, default=10.0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='definition',
            name='jupyter_notebook_lowest',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MS', 'Checkboxes'), ('SS', 'Multiple Choice'), ('TX', 'Text Answer')], default='TX', max_length=2),
        ),
        migrations.AlterField(
            model_name='submission',
            name='jupyter_score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, null=True),
        ),
    ]
